server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: service-bookmanager-java
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bookmanager-db
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:jpa.database-platform: org.hibernate.dialect.H2Dialect